### ISSUE TITLE
a guidance  plz

### ISSUE THREAD

**Issue by houmanka** [angelikatyborska/falling_blocks#1]
Hi, 
Thank you for sharing your project. I am trying to learn Phx live however there is no good resource beside the docs. 

Is it possible you write a small article on your falling blocks? 

Like a how to, or explaining how pieces fits together. 

Thanks

**Comment by angelikatyborska** [comment]
I am sorry I didn't respond sooner, I didn't notice when this issue was created.

I currently lack the time to write a LiveView tutorial... I found this tutorial on how to set up LiveView: [poeticoding.com/how-to-setup-phoenix-liveview](https://www.poeticoding.com/how-to-setup-phoenix-liveview/). Maybe this helps?

**Comment by szsoppa** [comment]
@houmanka You can also take a look at the series of tutorials where you'll build Messenger app step by step with Phoenix Live View: https://curiosum.dev/blog/elixir-phoenix-liveview-messenger-part-1
